# Generated by Django 2.1.5 on 2019-08-11 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='ADMIN', max_length=255)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.CharField(default='ADMIN', max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('popularity', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('director', models.CharField(db_index=True, max_length=100)),
                ('imdb_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('actors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None)),
            ],
            options={
                'db_table': 'movie_details',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='moviedetails',
            unique_together={('id', 'name')},
        ),
    ]
