# Generated by Django 2.1.5 on 2019-08-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='actors',
        ),
    ]
