# Generated by Django 2.1.5 on 2019-08-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_remove_moviedetails_actors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviedetails',
            options={'managed': True, 'ordering': ['id']},
        ),
    ]
